name: main_action
on: [push, pull_request]
jobs:
  test:
    uses: ./.github/workflows/test.yml
  build_eeps:
    needs: [test]
    uses: ./.github/workflows/build_eeps.yml
  build_EEF_packages:
    runs-on: ubuntu-latest
    needs: [build_eeps]
    env:
        TARGET: win64
    steps:
      - uses: hredan/eef-carefree-action@init
        with:
          target-os: ${{env.TARGET}}
